/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;


import Modelo.EspecialidadEnum;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import Modelo.EspecialidadEnum;
import Modelo.ProductosEnum;
import Modelo.Masajista;
import Modelo.Tratamiento;
import Persistencia.MasajistaData;
import Persistencia.TratamientoData;
/**
 *
 * @author abate
 */
public class BuscarTratamientoPorTipo extends javax.swing.JInternalFrame {
    private ArrayList<Tratamiento> listaT;
    private TratamientoData tratamientodata;
    private DefaultTableModel modeloTabla;

    public BuscarTratamientoPorTipo(){
        super("Buscar Tratamiento por Tipo", true, true, true, true);
        initComponents();

        tratamientodata = new TratamientoData();
        listaT = (ArrayList<Tratamiento>) tratamientodata.listarTratamientos();

        modeloTabla = new DefaultTableModel();
        cargarColumnasTablas();
        cargarTratamiento();
        tratamientoTablaTipos();

        // Listener para actualizar tabla al cambiar selección
        jcb_listadoTratam.addActionListener(e -> tratamientoTablaTipos());
    }

    // Cargar los valores del enum en el combo
    public void cargarTratamiento() {
        for (EspecialidadEnum especialidad : EspecialidadEnum.values()){
            jcb_listadoTratam.addItem(especialidad.toString());
        }
    }
    // Definir columnas de la tabla
    private void cargarColumnasTablas() {
        modeloTabla.addColumn("Nombre");
        modeloTabla.addColumn("Tipo");
        modeloTabla.addColumn("Detalle");
        modeloTabla.addColumn("Duración");
        modeloTabla.addColumn("Costo");
        tbl_tablaTratamientos.setModel(modeloTabla);
    }
    // Borrar todas las filas antes de recargar
    private void borrarFilaTabla() {
        int indice = modeloTabla.getRowCount() - 1;
        for (int i = indice; i >= 0; i--) {
            modeloTabla.removeRow(i);
        }
    }
    // Filtrar tratamientos por tipo seleccionado
    private void tratamientoTablaTipos() {
        borrarFilaTabla();
        String tipoSeleccionado = (String) jcb_listadoTratam.getSelectedItem();
        listaT = (ArrayList<Tratamiento>) tratamientodata.listarTratamientos();

        for (Tratamiento tratamiento : listaT) {

//            if (tratamiento.getEspecialidad()== tipoSeleccionado) {
            modeloTabla.addRow(new Object[]{
                tratamiento.getNombre(),
                tratamiento.getEspecialidad(), // muestra el enum
                tratamiento.getDetalle(),
                tratamiento.getDuracion(),
                tratamiento.getCosto()
            });

        }
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jL_titulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jcb_listadoTratam = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_tablaTratamientos = new javax.swing.JTable();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jL_titulo.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jL_titulo.setText("Tratamientos por tipo");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Tratamientos:");

        jcb_listadoTratam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_listadoTratamActionPerformed(evt);
            }
        });

        tbl_tablaTratamientos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_tablaTratamientos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jL_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(jcb_listadoTratam, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(268, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jL_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jcb_listadoTratam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcb_listadoTratamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_listadoTratamActionPerformed
        // TODO add your handling code here:
        tratamientoTablaTipos();
    }//GEN-LAST:event_jcb_listadoTratamActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarTratamientoPorTipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarTratamientoPorTipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarTratamientoPorTipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarTratamientoPorTipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscarTratamientoPorTipo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jL_titulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcb_listadoTratam;
    private javax.swing.JTable tbl_tablaTratamientos;
    // End of variables declaration//GEN-END:variables
}
