/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Estilo.EstiloVisual;
import Modelo.EspecialidadEnum;
import Modelo.Masajista;
import Modelo.Tratamiento;
import Persistencia.MasajistaData;
import Persistencia.TratamientoData;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

import Modelo.EspecialidadEnum;
import Modelo.Masajista;
import Persistencia.MasajistaData;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author abate
 */
public class BuscarMasajistaPorEspecialidad extends javax.swing.JInternalFrame {

    /**
     * Creates new form MasajistaDisponible
     */
    private ArrayList<Masajista> listaM;
    private MasajistaData masajistadata;
    private DefaultTableModel modeloTabla;

    public BuscarMasajistaPorEspecialidad() {
        super("Buscar Especialidad por Tipo", true, true, true, true);
        initComponents();
        EstiloVisual.aplicarEstiloPanel(jPanel1);
        EstiloVisual.aplicarEstiloTabla(tbl_tablaMasajistas);

        masajistadata = new MasajistaData();
        listaM = (ArrayList<Masajista>) masajistadata.listarMasajista();

        modeloTabla = new DefaultTableModel();
        cargarColumnasTablas();
        cargarTratamiento();
        especialidadTablaTipos();
    }

    // Cargar los valores del enum en el combo
    public void cargarTratamiento() {

        jcb_Especialidad.removeAllItems();
        jcb_Especialidad.addItem("Seleccione un tipo...");

        for (EspecialidadEnum especialidad : EspecialidadEnum.values()) {
            jcb_Especialidad.addItem(especialidad.toString());
        }
    }

    // Definir columnas de la tabla
    private void cargarColumnasTablas() {
        modeloTabla.addColumn("Matricula");
        modeloTabla.addColumn("NombreCompleto");
        modeloTabla.addColumn("Telefono");
        modeloTabla.addColumn("Especialidad");
        tbl_tablaMasajistas.setModel(modeloTabla);
    }

    // Borrar todas las filas antes de recargar
    private void borrarFilaTabla() {
        int indice = modeloTabla.getRowCount() - 1;
        for (int i = indice; i >= 0; i--) {
            modeloTabla.removeRow(i);
        }
    }

    // Filtrar tratamientos por tipo seleccionado
    private void especialidadTablaTipos() {
        borrarFilaTabla();

        String tipoSeleccionado = (String) jcb_Especialidad.getSelectedItem();
        if (tipoSeleccionado == null || tipoSeleccionado.equals("Seleccione un tipo...")) {
            return;
        }

        try {
            listaM = (ArrayList<Masajista>) masajistadata.listarMasajista();
            boolean encontrado = false;
            for (Masajista masajista : listaM) {
                if (masajista.getEspecialidad().toString().equalsIgnoreCase(tipoSeleccionado)) {

                    modeloTabla.addRow(new Object[]{
                        masajista.getMatricula(),
                        masajista.getNombreCompleto(), // muestra el enum
                        masajista.getTelefono(),
                        masajista.getEspecialidad()
                    });
                    encontrado = true;
                }

                if (masajistadata == null) {
                    JOptionPane.showMessageDialog(this, "Error interno: fuente de datos no disponible.");
                    return;
                }

            }

            if (!encontrado) {
                JOptionPane.showMessageDialog(this, "No se encontraron tratamientos del tipo seleccionado.");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al obtener Los Tratamientos: " + e.getMessage());
            return;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jL_Titulo = new javax.swing.JLabel();
        jcb_Especialidad = new javax.swing.JComboBox<>();
        jL_subtitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_tablaMasajistas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jL_Titulo.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jL_Titulo.setText("Buscar Masajistas por su Especialidad");

        jcb_Especialidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcb_Especialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_EspecialidadActionPerformed(evt);
            }
        });

        jL_subtitulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jL_subtitulo.setText("Especialidades");

        tbl_tablaMasajistas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_tablaMasajistas);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mano aceite.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jL_Titulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jL_subtitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jcb_Especialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jL_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_subtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcb_Especialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcb_EspecialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_EspecialidadActionPerformed
        // TODO add your handling code here:
        especialidadTablaTipos();
    }//GEN-LAST:event_jcb_EspecialidadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarMasajistaPorEspecialidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarMasajistaPorEspecialidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarMasajistaPorEspecialidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarMasajistaPorEspecialidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscarMasajistaPorEspecialidad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jL_Titulo;
    private javax.swing.JLabel jL_subtitulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcb_Especialidad;
    private javax.swing.JTable tbl_tablaMasajistas;
    // End of variables declaration//GEN-END:variables
}
