/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;
import java.time.LocalDate;
import Modelo.Cliente;
import Modelo.Dia_de_Spa;
import Modelo.Sesion;
import Persistencia.ClienteData;
import java.time.ZoneId;
import java.util.List;
import javax.swing.JOptionPane;
import Persistencia.Dia_de_SpaData;
import Persistencia.SesionData;
import Vista.GestionDeSesiones;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author abate
 */
public class CrearDiaDeSpa extends javax.swing.JInternalFrame {
private Dia_de_SpaData abmDiaDeSpa = new Dia_de_SpaData();
private DefaultTableModel modeloDias;
    /**
     * Creates new form CrearDiaDeSpa
     */
    
    public CrearDiaDeSpa() {
        initComponents();
        LlenarClientes();
        cargarTablaDias();
    }
   private void cargarTablaDias() {
    modeloDias = new DefaultTableModel();
    modeloDias.setColumnIdentifiers(new Object[]{
        "CodPack", "Fecha", "Cliente", "Preferencias", "Estado"
    });

    List<Dia_de_Spa> lista = abmDiaDeSpa.listarDia_de_Spa();

    for (Dia_de_Spa d : lista) {
        modeloDias.addRow(new Object[]{
            d.getCodPack(),
            d.getFechaYHora(),
            (d.getCliente() != null) ? d.getCliente().getNombreCompleto() : "Sin cliente",
            d.getPreferencias(),
            d.getEstado() ? "Activo" : "Inactivo"
        });
    }

    jtablaDiasSpa.setModel(modeloDias);
}
   private void limpiarFormulario() {
    jdcFecha.setDate(null);

    if (cmb_clientesActivos.getItemCount() > 0) {
        cmb_clientesActivos.setSelectedIndex(0);
    }

    jtfPreferencias.setText("");
    cbEstado.setSelected(true);
    TXFcodpack.setText("");

    btnGuardarSpa.setEnabled(true);
    btnActualizarSpa.setEnabled(false);
    ELIMINARSPA.setEnabled(false);
}
   
    public void LlenarClientes(){
     cmb_clientesActivos.removeAllItems(); 

    ClienteData cd = new ClienteData();
    List<Cliente> lista = cd.listarCliente();

    for (Cliente c : lista) {
        cmb_clientesActivos.addItem(c);
    }

    
    btnGuardarSpa.setEnabled(true);
    btnActualizarSpa.setEnabled(false);
    ELIMINARSPA.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jDesktopPane3 = new javax.swing.JDesktopPane();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbEstado = new javax.swing.JCheckBox();
        TXFcodpack = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cmb_clientesActivos = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jtfPreferencias = new javax.swing.JTextField();
        btnAgregarSesion = new javax.swing.JButton();
        ELIMINARSPA = new javax.swing.JButton();
        btnGuardarSpa = new javax.swing.JButton();
        jdcFecha = new com.toedter.calendar.JDateChooser();
        btnActualizarSpa = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnReportesSpa = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtablaDiasSpa = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("CREAR DIA DE SPA");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Cod pack");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Fecha");

        cbEstado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbEstado.setSelected(true);
        cbEstado.setText("Estado");

        TXFcodpack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXFcodpackActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Cliente");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Preferencias");

        btnAgregarSesion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAgregarSesion.setText("GESTIONAR SESION");
        btnAgregarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarSesionActionPerformed(evt);
            }
        });

        ELIMINARSPA.setText("Eliminar Dia de SPA");
        ELIMINARSPA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ELIMINARSPAActionPerformed(evt);
            }
        });

        btnGuardarSpa.setText("Guardar Dia de SPA");
        btnGuardarSpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarSpaActionPerformed(evt);
            }
        });

        btnActualizarSpa.setText("ACTUALIZAR DIA SPA");
        btnActualizarSpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarSpaActionPerformed(evt);
            }
        });

        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnReportesSpa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnReportesSpa.setText("REPORTES DIA DE SPA");
        btnReportesSpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesSpaActionPerformed(evt);
            }
        });

        jtablaDiasSpa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtablaDiasSpa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtablaDiasSpaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtablaDiasSpa);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel6.setText("DIAS DE SPA CREADOS");

        jDesktopPane3.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(cbEstado, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(TXFcodpack, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(cmb_clientesActivos, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(jtfPreferencias, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(btnAgregarSesion, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(ELIMINARSPA, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(btnGuardarSpa, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(jdcFecha, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(btnActualizarSpa, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(btnLimpiar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(btnReportesSpa, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane3Layout = new javax.swing.GroupLayout(jDesktopPane3);
        jDesktopPane3.setLayout(jDesktopPane3Layout);
        jDesktopPane3Layout.setHorizontalGroup(
            jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane3Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnAgregarSesion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jDesktopPane3Layout.createSequentialGroup()
                        .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane3Layout.createSequentialGroup()
                                .addGap(250, 250, 250)
                                .addComponent(jLabel3))
                            .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(TXFcodpack, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cbEstado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtfPreferencias, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cmb_clientesActivos, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jdcFecha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 741, Short.MAX_VALUE))))
                    .addComponent(jScrollPane2)
                    .addComponent(btnReportesSpa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jDesktopPane3Layout.createSequentialGroup()
                        .addComponent(btnGuardarSpa, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(btnActualizarSpa, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(ELIMINARSPA, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(355, 355, 355))
        );
        jDesktopPane3Layout.setVerticalGroup(
            jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel3)
                .addGap(40, 40, 40)
                .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jdcFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(34, 34, 34)
                .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmb_clientesActivos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtfPreferencias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(cbEstado)
                .addGap(32, 32, 32)
                .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TXFcodpack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(btnAgregarSesion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReportesSpa)
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarSpa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnActualizarSpa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ELIMINARSPA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jDesktopPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane2)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane3))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarSpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarSpaActionPerformed
     try {
        if (jdcFecha.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Seleccione una fecha");
            return;
        }
        Cliente cli = (Cliente) cmb_clientesActivos.getSelectedItem();
        if (cli == null || cli.getCod_cliente() == 0) {
            JOptionPane.showMessageDialog(this, "Seleccione un cliente");
            return;
        }

        LocalDate fecha = jdcFecha.getDate().toInstant()
                .atZone(ZoneId.systemDefault())
                .toLocalDate();

        Dia_de_Spa dia = new Dia_de_Spa(
                fecha,
                jtfPreferencias.getText(),
                cli,
                0.0,
                cbEstado.isSelected()
        );

        abmDiaDeSpa.agregarDiaSpa(dia);

        TXFcodpack.setText(String.valueOf(dia.getCodPack()));
        JOptionPane.showMessageDialog(this, "Dia de Spa guardado");

        cargarTablaDias();

    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Error al guardar: " + ex.getMessage());
    }

    }//GEN-LAST:event_btnGuardarSpaActionPerformed

    private void btnAgregarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarSesionActionPerformed
     if (TXFcodpack.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Guarda el dia primero");
        return;
    }
    int cod = Integer.parseInt(TXFcodpack.getText());

    GestionDeSesiones gs = new GestionDeSesiones(cod);
    this.getDesktopPane().add(gs);
    gs.setVisible(true);
    gs.toFront();

    }//GEN-LAST:event_btnAgregarSesionActionPerformed

    private void TXFcodpackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXFcodpackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXFcodpackActionPerformed

    private void ELIMINARSPAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ELIMINARSPAActionPerformed
        if (TXFcodpack.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Seleccione un dia");
            return;
        }

        int cod = Integer.parseInt(TXFcodpack.getText());

        SesionData sd = new SesionData();
        List<Sesion> sesiones = sd.listarSesionesPorCodPack(cod);

        if (!sesiones.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "No puedes eliminar este dia porque tiene sesiones asociadas, se debe eliminar la sesion");
            return;
        }

        int r = JOptionPane.showConfirmDialog(this,
                "Eliminar dia de spa " + cod + "?",
                "Confirmar", JOptionPane.YES_NO_OPTION);

        if (r == JOptionPane.YES_OPTION) {
            abmDiaDeSpa.eliminarDiadeSpa(cod);
            JOptionPane.showMessageDialog(this, "Dia eliminado");

            limpiarFormulario();
            cargarTablaDias();
            jtablaDiasSpa.clearSelection();
        }
    }//GEN-LAST:event_ELIMINARSPAActionPerformed

    private void btnActualizarSpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarSpaActionPerformed
       if (TXFcodpack.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Seleccione un Dia primero");
        return;
    }

         try {
        int cod = Integer.parseInt(TXFcodpack.getText());
        if (jdcFecha.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Seleccione una fecha");
            return;
        }
        Cliente cli = (Cliente) cmb_clientesActivos.getSelectedItem();
        if (cli == null || cli.getCod_cliente() == 0) {
            JOptionPane.showMessageDialog(this, "Seleccione un cliente");
            return;
        }

        LocalDate fecha = jdcFecha.getDate().toInstant()
                .atZone(ZoneId.systemDefault())
                .toLocalDate();

        Dia_de_Spa dia = new Dia_de_Spa(
                fecha,
                jtfPreferencias.getText(),
                cli,
                0.0,
                cbEstado.isSelected()
        );
        dia.setCodPack(cod);

        abmDiaDeSpa.actualizarDiaSpa(dia);

        JOptionPane.showMessageDialog(this, "Dia actualizado");
        cargarTablaDias();

    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Error al actualizar: " + ex.getMessage());
    }
    
    
    }//GEN-LAST:event_btnActualizarSpaActionPerformed

    private void jtablaDiasSpaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtablaDiasSpaMouseClicked
     int fila = jtablaDiasSpa.getSelectedRow();
    if (fila == -1) return;

    int cod = (int) modeloDias.getValueAt(fila, 0);

    Dia_de_Spa dia = abmDiaDeSpa.buscarDia(cod);
    if (dia == null) {
        JOptionPane.showMessageDialog(this, "No encontrado");
        return;
    }

    jdcFecha.setDate(java.sql.Date.valueOf(dia.getFechaYHora()));
    cmb_clientesActivos.setSelectedItem(dia.getCliente());
    jtfPreferencias.setText(dia.getPreferencias());
    cbEstado.setSelected(dia.getEstado());
    TXFcodpack.setText(String.valueOf(dia.getCodPack()));

    btnGuardarSpa.setEnabled(false);
    btnActualizarSpa.setEnabled(true);
    ELIMINARSPA.setEnabled(true);
    }//GEN-LAST:event_jtablaDiasSpaMouseClicked

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarFormulario();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnReportesSpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesSpaActionPerformed
    int fila = jtablaDiasSpa.getSelectedRow();
    
    if (fila == -1) {
        JOptionPane.showMessageDialog(this,
                "Seleccione un Día de Spa de la tabla para ver el reporte.");
        return;
    }

    int cod = (int) modeloDias.getValueAt(fila, 0);

    ReporteDiaDeSpa reporte = new ReporteDiaDeSpa(cod);
    this.getDesktopPane().add(reporte);
    reporte.setVisible(true);
    reporte.toFront();       
    }//GEN-LAST:event_btnReportesSpaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearDiaDeSpa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearDiaDeSpa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearDiaDeSpa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearDiaDeSpa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
             new CrearDiaDeSpa().setVisible(true);
            }
        });
    };
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ELIMINARSPA;
    private javax.swing.JTextField TXFcodpack;
    private javax.swing.JButton btnActualizarSpa;
    private javax.swing.JButton btnAgregarSesion;
    private javax.swing.JButton btnGuardarSpa;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnReportesSpa;
    private javax.swing.JCheckBox cbEstado;
    private javax.swing.JComboBox<Cliente> cmb_clientesActivos;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JDesktopPane jDesktopPane3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private com.toedter.calendar.JDateChooser jdcFecha;
    private javax.swing.JTable jtablaDiasSpa;
    private javax.swing.JTextField jtfPreferencias;
    // End of variables declaration//GEN-END:variables
}

