/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Estilo.EstiloVisual;
import Modelo.Cliente;
import Persistencia.ClienteData;
import javax.swing.JOptionPane;

/**
 *
 * @author abate
 */
public class GestionClientes extends javax.swing.JInternalFrame {

    /**
     * Creates new form GestionClientes
     */
    public GestionClientes() {
        initComponents();
        EstiloVisual.aplicarEstiloJDPanel(jDesktopPane1);
        EstiloVisual.aplicarEstiloBoton(btnBuscar);
        EstiloVisual.aplicarEstiloBoton(btnAgregar);
        EstiloVisual.aplicarEstiloBoton(btnModificar);
        EstiloVisual.aplicarEstiloBoton(btnLimpiar);
         EstiloVisual.aplicarEstiloBoton(btnEliminar);
        
    }
    
    private void limpiarCampos() {
//  Vaciar los campos de texto
    jtfDniCliente.setText("");
    jtfNombreCliente.setText("");
    jtfTelefono.setText("");
    jTfEdad.setText("");
    jtfAfecciones.setText("");
    CBEstado.setSelected(false);
    jtfCodigoCliente.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jL_Titulo = new javax.swing.JLabel();
        jTfEdad = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtfDniCliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtfNombreCliente = new javax.swing.JTextField();
        jtfCodigoCliente = new javax.swing.JTextField();
        jtfAfecciones = new javax.swing.JTextField();
        jtfTelefono = new javax.swing.JTextField();
        CBEstado = new javax.swing.JCheckBox();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jL_Titulo.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        jL_Titulo.setText("GESTION CLIENTE");

        jLabel2.setText("Nombre del cliente");

        jLabel3.setText("Codigo cliente");

        jLabel4.setText("DNI");

        jLabel5.setText("Edad");

        jLabel6.setText("Telefono");

        jLabel7.setText("Afecciones");

        jLabel8.setText("Estado");

        jtfCodigoCliente.setEditable(false);

        btnAgregar.setText("AGREGAR");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnModificar.setText("MODIFICAR");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bambuchico_1.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jDesktopPane1.setLayer(jL_Titulo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jTfEdad, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jtfDniCliente, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jtfNombreCliente, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jtfCodigoCliente, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jtfAfecciones, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jtfTelefono, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(CBEstado, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnAgregar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnModificar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnBuscar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnLimpiar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnEliminar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(btnAgregar))
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jL_Titulo))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfAfecciones, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                            .addComponent(jtfDniCliente)
                                            .addGap(18, 18, 18)
                                            .addComponent(btnBuscar))
                                        .addComponent(jTfEdad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(CBEstado)))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(btnModificar)
                                .addGap(92, 92, 92)
                                .addComponent(btnLimpiar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnEliminar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jL_Titulo)
                .addGap(73, 73, 73)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jtfCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jtfDniCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscar))
                        .addGap(18, 18, 18)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTfEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jtfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfAfecciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(27, 27, 27)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(CBEstado))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAgregar)
                            .addComponent(btnModificar)
                            .addComponent(btnLimpiar)
                            .addComponent(btnEliminar)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        try {
            if (jtfDniCliente.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Debe ingresar un DNI para borrar.");
                return;
            }

            int dni = Integer.parseInt(jtfDniCliente.getText().trim());
            ClienteData clienteData = new ClienteData();

            Cliente clienteEncontrado = clienteData.buscarCliente(dni);

            if (clienteEncontrado != null) {

                int respuesta = JOptionPane.showConfirmDialog(this,
                        "¿Esta seguro que desea eliminar al cliente " + clienteEncontrado.getNombreCompleto() + "?",
                        "Confirmar",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.WARNING_MESSAGE); // Icono de advertencia

                if (respuesta == JOptionPane.YES_OPTION) {
                    clienteData.eliminarCliente(dni);

                    JOptionPane.showMessageDialog(this, "Cliente eliminado.");
                    limpiarCampos();
                }

            } else {
                JOptionPane.showMessageDialog(this, "No se encuentra un cliente con ese DNI.");
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ingrese un num valido en el campo DNI.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al eliminar: " + e.getMessage());
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        try {
            ClienteData clienteData = new ClienteData();
            int dni = Integer.parseInt(jtfDniCliente.getText());
            Cliente cliente = clienteData.buscarCliente(dni);
            if (cliente != null) {
                jtfCodigoCliente.setText(String.valueOf(cliente.getCod_cliente()));
                jtfNombreCliente.setText(cliente.getNombreCompleto());
                jtfTelefono.setText(cliente.getTelefono());
                jTfEdad.setText(String.valueOf(cliente.getEdad()));
                jtfAfecciones.setText(cliente.getAfecciones());
                CBEstado.setSelected(cliente.isEstado());

            if (!cliente.isEstado()) {
            JOptionPane.showMessageDialog(this, "Este cliente figura como Inactivo/Dado de baja.");
        }    
            } else {
                JOptionPane.showMessageDialog(this, "No se encuentra el DNI ingresado: "+ dni);
                limpiarCampos();
                //Mantener el Campo DNI Escrito
                jtfDniCliente.setText(String.valueOf(dni));
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ingrese un num Valido para Buscar DNI");
        jtfDniCliente.setText("");
        }catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Error al buscar: " + e.getMessage());
}

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
try {   
            ClienteData clienteData = new ClienteData();

            // Validar DNI
            if (jtfDniCliente.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "El campo DNI no puede estar vacio.");
                return;
            }

            int dni = Integer.parseInt(jtfDniCliente.getText().trim());
            Cliente clienteOriginal = clienteData.buscarCliente(dni);
            if (clienteOriginal == null) {
                JOptionPane.showMessageDialog(this, "No existe ningun cliente con el DNI ingresado");
                return;
            }

            // Validar demas Campos
            String nombre_completo = jtfNombreCliente.getText().trim();
            String telefono = jtfTelefono.getText().trim();
            String afecciones = jtfAfecciones.getText().trim();
            String edadTexto = jTfEdad.getText().trim();

            // Validar Vacios
            if (nombre_completo.isEmpty() || telefono.isEmpty()) {
                JOptionPane.showMessageDialog(this, "El nombre y el telefono son obligatorios.");
                return;
            }

            // Validar Edad
            if (edadTexto.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Debe ingresar la edad.");
                return;
            }

            int edad = Integer.parseInt(edadTexto);

            if (edad < 0 || edad > 120) { //valida edad
                JOptionPane.showMessageDialog(this, "Ingrese una edad valida.");
                return;
            }

            //Confirmaciones
            int confirmacion = JOptionPane.showConfirmDialog(this,
                    "¿Esta seguro de modificar los datos del cliente " + nombre_completo + "?",
                    "Confirmar Modificacion",
                    JOptionPane.YES_NO_OPTION);

            if (confirmacion == JOptionPane.YES_OPTION) {
                //Actualiza
                boolean estado = CBEstado.isSelected();
                Cliente cliente = new Cliente(dni, nombre_completo, telefono, edad, afecciones, estado);

                Cliente clienteModificado = new Cliente(dni, nombre_completo, telefono, edad, afecciones, estado);

                //Traer ID del cliente BD
                clienteModificado.setCod_cliente(clienteOriginal.getCod_cliente());

                clienteData.actualizarCliente(clienteModificado);
                JOptionPane.showMessageDialog(this, "Cliente modificado.");
                limpiarCampos();
            }

        } catch (NumberFormatException e) {
            // atrapa Errores Edad y DNI
            JOptionPane.showMessageDialog(this, "Error de formato: Verifique que DNI y Edad contengan solo numeros enteros.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrio un error inesperado: " + e.getMessage());
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        try {
            String nombre_completo = jtfNombreCliente.getText().trim();
            String telefono = jtfTelefono.getText().trim();
            String afecciones = jtfAfecciones.getText().trim();

            if (nombre_completo.isEmpty()) {
                JOptionPane.showMessageDialog(this, "El campo Nombre no puede estar vacio.");
                return;
            }

            if (telefono.isEmpty()) {
                JOptionPane.showMessageDialog(this, "El campo Telefono no puede estar vacio.");
                return;
            }
            if (jtfDniCliente.getText().trim().isEmpty() || jTfEdad.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Debe completar los campos DNI y Edad.");
                return;
            }

            int dni = Integer.parseInt(jtfDniCliente.getText());
            int edad = Integer.parseInt(jTfEdad.getText());
            boolean estado = CBEstado.isSelected();

            ClienteData clienteData = new ClienteData();
            Cliente cliente = new Cliente(dni, nombre_completo, telefono, edad, afecciones, estado);
            clienteData.agregarCliente(cliente);

            JOptionPane.showMessageDialog(this, "Cliente agregado exitosamente.");
            //limpiaCampos
            limpiarCampos();

        } catch (NumberFormatException e) {
            // Este error salta si el DNI o la Edad tienen letras o simbolos
            JOptionPane.showMessageDialog(this, "Error de formato: Verifique que DNI y Edad sean solo num.");
        } catch (Exception e) {
            // Captura errores inesperados
            JOptionPane.showMessageDialog(this, "Ocurrio un error al guardar: " + e.getMessage());
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CBEstado;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jL_Titulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTfEdad;
    private javax.swing.JTextField jtfAfecciones;
    private javax.swing.JTextField jtfCodigoCliente;
    private javax.swing.JTextField jtfDniCliente;
    private javax.swing.JTextField jtfNombreCliente;
    private javax.swing.JTextField jtfTelefono;
    // End of variables declaration//GEN-END:variables
}
