/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.Consultorio;
import Modelo.Dia_de_Spa;
import Modelo.Instalacion;
import Modelo.Masajista;
import Modelo.Sesion;
import Modelo.Tratamiento;
import Persistencia.ConsultorioData;
import Persistencia.InstalacionData;
import Persistencia.MasajistaData;
import Persistencia.SesionData;
import Persistencia.TratamientoData;
import java.util.ArrayList;
import java.sql.Time;
import java.time.LocalDate;
import java.time.LocalTime;
import javax.swing.JOptionPane;
import Persistencia.Dia_de_SpaData;

/**
 *
 * @author abate
 */
public class GestionDeSesiones extends javax.swing.JInternalFrame {
    private ArrayList<Tratamiento> listaTratamiento;
    private ArrayList<Consultorio> listaConsultorio;
    private ArrayList<Masajista> listaMasajista;
    private ArrayList<Instalacion> listaInstalacion;
    private ArrayList<Dia_de_Spa> listaDiaDeSpa;
    private Dia_de_SpaData abmDia_de_Spa;
    private InstalacionData abmInstalacion;
    private MasajistaData abmMasajista;
    private ConsultorioData abmConsultorio;
    private TratamientoData abmTratamiento;
    private int codigoSeleccionado;
    
    /**
     * Creates new form GestionDeSesiones
     */
    public GestionDeSesiones() {
        initComponents();
        abmConsultorio = new ConsultorioData();
        abmTratamiento = new TratamientoData();
        abmMasajista = new MasajistaData();
        abmInstalacion = new InstalacionData();
        abmDia_de_Spa = new Dia_de_SpaData();
        listaDiaDeSpa = (ArrayList<Dia_de_Spa>) abmDia_de_Spa.listarDia_de_Spa();
        listaTratamiento = (ArrayList<Tratamiento>) abmTratamiento.listarTratamientos();
        listaConsultorio = (ArrayList<Consultorio>) abmConsultorio.listarConsultorios();
        listaMasajista = (ArrayList<Masajista>) abmMasajista.listarMasajista();
        listaInstalacion = (ArrayList<Instalacion>) abmInstalacion.listarInstalaciones();
        cargarComboTratamientos();
        cargarComboConsultorio();
        cargarComboMasajista();
        cargarComboInstalacion();
        cargarComboDiaDeSpa();
    }
    
    public GestionDeSesiones(int codPack) {
        initComponents();
        this.codigoSeleccionado = codPack;
        inicializarDatos(); 
        seleccionarDiaDeSpa(); 
    }
        private void inicializarDatos() {
        abmConsultorio = new ConsultorioData();
        abmTratamiento = new TratamientoData();
        abmMasajista = new MasajistaData();
        abmInstalacion = new InstalacionData();
        abmDia_de_Spa = new Dia_de_SpaData();

        listaDiaDeSpa = (ArrayList<Dia_de_Spa>) abmDia_de_Spa.listarDia_de_Spa();
        listaTratamiento = (ArrayList<Tratamiento>) abmTratamiento.listarTratamientos();
        listaConsultorio = (ArrayList<Consultorio>) abmConsultorio.listarConsultorios();
        listaMasajista = (ArrayList<Masajista>) abmMasajista.listarMasajista();
        listaInstalacion = (ArrayList<Instalacion>) abmInstalacion.listarInstalaciones();

        cargarComboTratamientos();
        cargarComboConsultorio();
        cargarComboMasajista();
        cargarComboInstalacion();
        cargarComboDiaDeSpa();
    }
        private void seleccionarDiaDeSpa() {
        for (int i = 0; i < jCbCodPaquete.getItemCount(); i++) {
            Dia_de_Spa dia = jCbCodPaquete.getItemAt(i);
            if (dia.getCodPack() == codigoSeleccionado) {
                jCbCodPaquete.setSelectedIndex(i);
                return;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jservicio = new javax.swing.JLabel();
        jServicio1 = new javax.swing.JLabel();
        jBtnAgregar = new javax.swing.JButton();
        jServicio2 = new javax.swing.JLabel();
        jServicio3 = new javax.swing.JLabel();
        jServicio4 = new javax.swing.JLabel();
        jCbmasajista = new javax.swing.JComboBox<>();
        jServicio5 = new javax.swing.JLabel();
        jCheckEstado = new javax.swing.JCheckBox();
        jBtnBorrar = new javax.swing.JButton();
        JBtnModificar = new javax.swing.JButton();
        jCbtratamiento = new javax.swing.JComboBox<>();
        jCbconsultorio = new javax.swing.JComboBox<>();
        jTfhoraInicio = new javax.swing.JTextField();
        jTfhoraFin = new javax.swing.JTextField();
        jServicio6 = new javax.swing.JLabel();
        jCbInstalacion = new javax.swing.JComboBox<>();
        jServicio7 = new javax.swing.JLabel();
        jCbCodPaquete = new javax.swing.JComboBox<>();
        jServicio8 = new javax.swing.JLabel();
        jTfCodSesion = new javax.swing.JTextField();
        jBtnBuscar = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel2.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        jLabel2.setText("Agregar Sesiones");

        jservicio.setText("Tipo de tratamiento:");

        jServicio1.setText("Hora Inicio:");

        jBtnAgregar.setText("Agregar");
        jBtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAgregarActionPerformed(evt);
            }
        });

        jServicio2.setText("Hora Final:");

        jServicio3.setText("Consultorio:");

        jServicio4.setText("Masajista:");

        jCbmasajista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbmasajistaActionPerformed(evt);
            }
        });

        jServicio5.setText("Estado:");

        jBtnBorrar.setText("Borrar");
        jBtnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBorrarActionPerformed(evt);
            }
        });

        JBtnModificar.setText("Modificar");
        JBtnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnModificarActionPerformed(evt);
            }
        });

        jServicio6.setText("Instalacion:");

        jCbInstalacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbInstalacionActionPerformed(evt);
            }
        });

        jServicio7.setText("Cod. Paquete:");

        jCbCodPaquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbCodPaqueteActionPerformed(evt);
            }
        });

        jServicio8.setText("Buscar Sesion:");

        jBtnBuscar.setText("Buscar");
        jBtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jServicio1)
                                    .addComponent(jservicio)
                                    .addComponent(jServicio3)
                                    .addComponent(jServicio4)
                                    .addComponent(jServicio6)
                                    .addComponent(jServicio7)
                                    .addComponent(jServicio8))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTfhoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jServicio2)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTfhoraFin))
                                    .addComponent(jCbmasajista, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jCbtratamiento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jCbconsultorio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jCbInstalacion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jCbCodPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jTfCodSesion)
                                        .addGap(18, 18, 18)
                                        .addComponent(jBtnBuscar))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jServicio5)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckEstado))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jBtnAgregar)
                                .addGap(67, 67, 67)
                                .addComponent(JBtnModificar)
                                .addGap(95, 95, 95)
                                .addComponent(jBtnBorrar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(jLabel2)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTfCodSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jServicio8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jservicio)
                    .addComponent(jCbtratamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jServicio1)
                    .addComponent(jServicio2)
                    .addComponent(jTfhoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTfhoraFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jServicio3)
                    .addComponent(jCbconsultorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jServicio4)
                    .addComponent(jCbmasajista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jServicio6)
                    .addComponent(jCbInstalacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCbCodPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jServicio7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jServicio5)
                    .addComponent(jCheckEstado))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBtnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAgregarActionPerformed
        // TODO add your handling code here:
        try {
            SesionData sd = new SesionData();
            
            //----CONTROL DE LA HORA
            String horaInicioStr = jTfhoraInicio.getText();
            String horaFinStr = jTfhoraFin.getText();
            int horaInicioInt;
            int horaFinInt;

            
            Tratamiento tratamiento = (Tratamiento) jCbtratamiento.getSelectedItem();
            if (tratamiento == null) {
                JOptionPane.showMessageDialog(this, "Debe seleccionar un tratamiento primero");
                return;
            }

            try {
                horaInicioInt = Integer.parseInt(horaInicioStr);
                horaFinInt = Integer.parseInt(horaFinStr);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, 
                    "Error al ingresar la hora, ingrese un numero dependiendo la hora que sea");
                return;
            }

            int duracionAgendada = horaFinInt - horaInicioInt; 
            int duracionRequerida = tratamiento.getDuracion();

            if (duracionAgendada != duracionRequerida) {
                JOptionPane.showMessageDialog(this, 
                    "La duración de la sesión no coincide con la del tratamiento.\n\n" +
                    "Duración Agendada: " + duracionAgendada + " hora(s) (de " + horaInicioInt + " a " + horaFinInt + ")\n" +
                    "Duración Tratamiento: " + duracionRequerida + " hora(s)");
                return;
            }
            
            // Time recibe HH:mm:ss, con esto valido si ingresa solo la hora
            if (horaInicioStr.length() <= 2) {
                horaInicioStr += ":00:00"; // agrega minutos y segundos para que quede en el formato correcto que pide Time
            }
            // Aca si ingresa HH:mm
            else if (horaInicioStr.length() == 5) {
                horaInicioStr += ":00"; // agrega los segundos
            }
            // Hacemos lo mismo para la hora de fin
            if (horaFinStr.length() <= 2) {
                horaFinStr += ":00:00";
            } else if (horaFinStr.length() == 5) {
                horaFinStr += ":00";
            }
            Time horaInicio = Time.valueOf(horaInicioStr);
            Time horaFin = Time.valueOf(horaFinStr);
            if (!horaFin.after(horaInicio)) {
                JOptionPane.showMessageDialog(this,"La hora final debe ser posterior a la de inicio");
                return;
            }
            //CONTROL DE LA HORA----
            
            
            Consultorio consultorio = (Consultorio) jCbconsultorio.getSelectedItem();
            Masajista masajista = (Masajista) jCbmasajista.getSelectedItem();
            Instalacion instalacion = (Instalacion) jCbInstalacion.getSelectedItem();
            
            //VALIDACION DE LA ESPECIALIDAD
            Dia_de_Spa diaDeSpa = (Dia_de_Spa) jCbCodPaquete.getSelectedItem();
            if (masajista.getEspecialidad() != tratamiento.getEspecialidad()) {
                JOptionPane.showMessageDialog(this,"El masajista no tiene la especialidad requerida para este tratamiento.\n\n" +
                    "Masajista: " + masajista.getEspecialidad() + "\n" +
                    "Tratamiento: " + tratamiento.getEspecialidad(), 
                    "Especialidad no coincide", 
                    JOptionPane.ERROR_MESSAGE);
                return; // Detiene la operación
            }
            
            
            boolean estado = jCheckEstado.isSelected();
            
            /*if (tratamiento == null || consultorio == null || masajista == null || instalacion == null || diaDeSpa == null) {
                JOptionPane.showMessageDialog(this, "Debe seleccionar algun dato");
                return;
            }*/
            
            LocalDate fechaDiaDeSpa = diaDeSpa.getFechaYHora();
            // validamos si masajista esta ocupado
            if (sd.masajistaOcupado(masajista.getCod_Masajista(), fechaDiaDeSpa, horaInicio, horaFin)) {
                JOptionPane.showMessageDialog(this,"El masajista " + masajista.getNombreCompleto() + " esta ocupado en esa fecha y horario");
                return;
            }

            // validamos si el consultorio esta ocupado
            if (sd.consultorioOcupado(consultorio.getCodConsultorio(), fechaDiaDeSpa, horaInicio, horaFin)) {
                JOptionPane.showMessageDialog(this,"El consultorio " + consultorio.toString() + " esta ocupado en esa fecha y horario.");
                return;
            }
            
            // validamos si la instalacion esta ocupada
            if (sd.instalacionOcupada(instalacion.getCodInstal(), fechaDiaDeSpa, horaInicio, horaFin)) {
                JOptionPane.showMessageDialog(this,"La instalacion " + instalacion.getNombre() + " esta ocupada en esa fecha y horario.");
                return;
            }
            
            Sesion sesion = new Sesion(horaInicio, horaFin, tratamiento, consultorio, masajista, instalacion, diaDeSpa , estado);
            sd.agregarSesion(sesion);
            
            jTfhoraInicio.setText("");
            jTfhoraFin.setText("");
            jCheckEstado.setSelected(false);
            jCbtratamiento.setSelectedIndex(0);
            jCbtratamiento.setSelectedIndex(-1); // Deselecciona los combos
            jCbconsultorio.setSelectedIndex(-1);
            jCbmasajista.setSelectedIndex(-1);
            jCbInstalacion.setSelectedIndex(-1);
            jCbCodPaquete.setSelectedIndex(-1);
            
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, "Error en el formato de hora. Use HH:mm:ss (ej: 14:30:00).");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al agregar la sesion");
        }
    }//GEN-LAST:event_jBtnAgregarActionPerformed

    private void jCbmasajistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbmasajistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCbmasajistaActionPerformed

    private void jBtnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBorrarActionPerformed
        // TODO add your handling code here:
        try {
            int codSesion = Integer.parseInt(jTfCodSesion.getText());

            int respuesta = JOptionPane.showConfirmDialog(this, 
                    "Estas seguro de eliminar la sesion " + codSesion + "?");

            SesionData sd = new SesionData();
            sd.eliminarSesion(codSesion);

            jTfCodSesion.setText("");
            jTfhoraInicio.setText("");
            jTfhoraFin.setText("");
            jCheckEstado.setSelected(false);
            jCbtratamiento.setSelectedIndex(-1); // Deselecciona los combos
            jCbconsultorio.setSelectedIndex(-1);
            jCbmasajista.setSelectedIndex(-1);
            jCbInstalacion.setSelectedIndex(-1);
            jCbCodPaquete.setSelectedIndex(-1);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "No existe esa sesion");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al eliminar la sesion: " + e.getMessage());
        }
        
    }//GEN-LAST:event_jBtnBorrarActionPerformed

    private void JBtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnModificarActionPerformed
        // TODO add your handling code here:
        try {
            SesionData sd = new SesionData();

            int codSesion;
            try {
                codSesion = Integer.parseInt(jTfCodSesion.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Numero de sesion no existe");
                return;
            }
            String horaInicioStr = jTfhoraInicio.getText().trim();
            String horaFinStr = jTfhoraFin.getText().trim();
            Tratamiento tratamiento = (Tratamiento) jCbtratamiento.getSelectedItem();

            int horaInicioInt = Integer.parseInt(horaInicioStr);
            int horaFinInt = Integer.parseInt(horaFinStr);
            int duracionAgendada = horaFinInt - horaInicioInt; 
            int duracionRequerida = tratamiento.getDuracion();

            if (duracionAgendada != duracionRequerida) {
                 JOptionPane.showMessageDialog(this, "La duracion agendada es distinta a la requerida");
                return;
            }
            if (horaFinInt <= horaInicioInt) {
                JOptionPane.showMessageDialog(this, "La hora final debe ser posterior a la de inicio");
                return;
            }

            if (horaInicioStr.length() <= 2) {
                horaInicioStr += ":00:00";
            }
            else if (horaInicioStr.length() == 5) {
                horaInicioStr += ":00"; 
            }
            if (horaFinStr.length() <= 2) {
                horaFinStr += ":00:00";
            } else if (horaFinStr.length() == 5) {
                horaFinStr += ":00";
            }
            Time horaInicio = Time.valueOf(horaInicioStr);
            Time horaFin = Time.valueOf(horaFinStr);

            Consultorio consultorio = (Consultorio) jCbconsultorio.getSelectedItem();
            Masajista masajista = (Masajista) jCbmasajista.getSelectedItem();
            Instalacion instalacion = (Instalacion) jCbInstalacion.getSelectedItem();
            Dia_de_Spa diaDeSpa = (Dia_de_Spa) jCbCodPaquete.getSelectedItem();
            boolean estado = jCheckEstado.isSelected();
            LocalDate fechaDeLaSesion = diaDeSpa.getFechaYHora();

            if (masajista.getEspecialidad() != tratamiento.getEspecialidad()) {
                JOptionPane.showMessageDialog(this, "Especialidad no coincide.");
                return; 
            }
            
            if (sd.masajistaOcupado(masajista.getCod_Masajista(), fechaDeLaSesion, horaInicio, horaFin, codSesion)) {
                JOptionPane.showMessageDialog(this, "El masajista " + masajista.getNombreCompleto() + " esta ocupado en esa fecha y horario");
                return; 
            }
            if (sd.consultorioOcupado(consultorio.getCodConsultorio(), fechaDeLaSesion, horaInicio, horaFin, codSesion)) {
                JOptionPane.showMessageDialog(this, "El consultorio numero " + consultorio.getNroConsultorio() + " esta ocupado en esa fecha y horario");
                return; 
            }
            if (sd.instalacionOcupada(instalacion.getCodInstal(), fechaDeLaSesion, horaInicio, horaFin, codSesion)) {
                JOptionPane.showMessageDialog(this, "La instalacion " + instalacion.getNombre() + " esta ocupada en esa fecha y horario");
                return; 
            }

            Sesion sesion = new Sesion(horaInicio, horaFin, tratamiento, consultorio, masajista, instalacion, diaDeSpa, estado);
            sesion.setCodSesion(codSesion);
            
            sd.actualizarSesion(sesion);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al modificar la sesion" + e.getMessage());
        }
    }//GEN-LAST:event_JBtnModificarActionPerformed

    private void jCbInstalacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbInstalacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCbInstalacionActionPerformed

    private void jCbCodPaqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbCodPaqueteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCbCodPaqueteActionPerformed

    private void jBtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBuscarActionPerformed
        // TODO add your handling code here:
        try {
            SesionData sd = new SesionData();
            int codSesion = Integer.parseInt(jTfCodSesion.getText());

            // Asumiendo que tienes un método buscarSesiones() en SesionData
            Sesion sesionEncontrada = sd.buscarSesiones(codSesion); 

            if (sesionEncontrada != null) {
                // Llenar campos de texto
                jTfhoraInicio.setText(sesionEncontrada.getFechaHoraInicio().toString().substring(0, 5)); // Muestra "HH:mm"
                jTfhoraFin.setText(sesionEncontrada.getFechaHoraFin().toString().substring(0, 5));
                jCheckEstado.setSelected(sesionEncontrada.isEstado());

                // --- Lógica para seleccionar en los ComboBox ---
                // (Esto busca el objeto en tu lista que coincida con el ID de la sesión)

                for (Tratamiento t : listaTratamiento) {
                    if (t.getCodTratam() == sesionEncontrada.getTratamiento().getCodTratam()) {
                        jCbtratamiento.setSelectedItem(t);
                        break;
                    }
                }

                for (Consultorio c : listaConsultorio) {
                    if (c.getCodConsultorio() == sesionEncontrada.getConsultorio().getCodConsultorio()) {
                        jCbconsultorio.setSelectedItem(c);
                        break;
                    }
                }

                for (Masajista m : listaMasajista) {
                    if (m.getCod_Masajista() == sesionEncontrada.getMasajista().getCod_Masajista()) {
                        jCbmasajista.setSelectedItem(m);
                        break;
                    }
                }

                for (Instalacion i : listaInstalacion) {
                    if (i.getCodInstal() == sesionEncontrada.getInstalaciones().getCodInstal()) {
                        jCbInstalacion.setSelectedItem(i);
                        break;
                    }
                }

                for (Dia_de_Spa d : listaDiaDeSpa) {
                    if (d.getCodPack() == sesionEncontrada.getDiaDeSpa().getCodPack()) {
                        jCbCodPaquete.setSelectedItem(d);
                        break;
                    }
                }

            } else {
                JOptionPane.showMessageDialog(this, "No se encontró ninguna sesión con ese código.");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ingrese un código de sesión numérico válido.");
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this, "Error. La sesión encontrada tiene datos nulos. Verifique su método buscarSesiones()");
        }

    }//GEN-LAST:event_jBtnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionDeSesiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionDeSesiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionDeSesiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionDeSesiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionDeSesiones().setVisible(true);
            }
        });
    }

    
    private void cargarComboTratamientos() {
        for (Tratamiento tratamiento : listaTratamiento) {
            jCbtratamiento.addItem(tratamiento);
        }
    }
    
    private void cargarComboConsultorio(){
        for (Consultorio consultorio : listaConsultorio) {
            jCbconsultorio.addItem(consultorio);
        }
    }
    
    private void cargarComboMasajista(){
        for (Masajista masajista : listaMasajista) {
            jCbmasajista.addItem(masajista);
        }
    }
    
    private void cargarComboInstalacion(){
        for (Instalacion instalacion : listaInstalacion) {
            jCbInstalacion.addItem(instalacion);
        }
    }
    
    private void cargarComboDiaDeSpa(){
        for (Dia_de_Spa diaDeSpa : listaDiaDeSpa) {
            jCbCodPaquete.addItem(diaDeSpa);
            
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBtnModificar;
    private javax.swing.JButton jBtnAgregar;
    private javax.swing.JButton jBtnBorrar;
    private javax.swing.JButton jBtnBuscar;
    private javax.swing.JComboBox<Dia_de_Spa> jCbCodPaquete;
    private javax.swing.JComboBox<Instalacion> jCbInstalacion;
    private javax.swing.JComboBox<Consultorio> jCbconsultorio;
    private javax.swing.JComboBox<Masajista> jCbmasajista;
    private javax.swing.JComboBox<Tratamiento> jCbtratamiento;
    private javax.swing.JCheckBox jCheckEstado;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jServicio1;
    private javax.swing.JLabel jServicio2;
    private javax.swing.JLabel jServicio3;
    private javax.swing.JLabel jServicio4;
    private javax.swing.JLabel jServicio5;
    private javax.swing.JLabel jServicio6;
    private javax.swing.JLabel jServicio7;
    private javax.swing.JLabel jServicio8;
    private javax.swing.JTextField jTfCodSesion;
    private javax.swing.JTextField jTfhoraFin;
    private javax.swing.JTextField jTfhoraInicio;
    private javax.swing.JLabel jservicio;
    // End of variables declaration//GEN-END:variables
}
