/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Estilo.EstiloVisual;
import Modelo.Consultorio;
import Persistencia.ConsultorioData;
import javax.swing.JOptionPane;

/**
 *
 * @author abate
 */
public class GestionConsultorios extends javax.swing.JInternalFrame {

    /**
     * Creates new form GestionConsultorios
     */
    public GestionConsultorios() {
        initComponents();
        EstiloVisual.aplicarEstiloJDPanel(jDesktopPane1);
        EstiloVisual.aplicarEstiloBoton(btnBorrar);
        EstiloVisual.aplicarEstiloBoton(btnBuscar);
        EstiloVisual.aplicarEstiloBoton(btnAgregar);
        EstiloVisual.aplicarEstiloBoton(btnModificar);
        EstiloVisual.aplicarEstiloBoton(btnLimpiar);
    }

     private void limpiarCampos() {
//  Vaciar los campos de texto
        JTFnumeroConsultorio.setText("");
        jtfCodigoConsul.setText("");
        JtfEquipamientos.setText("");
        jtfUsos.setText("");
        CBEstado.setSelected(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JTFnumeroConsultorio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtfCodigoConsul = new javax.swing.JTextField();
        JtfEquipamientos = new javax.swing.JTextField();
        jtfUsos = new javax.swing.JTextField();
        CBEstado = new javax.swing.JCheckBox();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Gestión de Consultorios");

        jLabel2.setText("Numero de Consultorio");

        jLabel3.setText("Codigo");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Equipamientos");

        jLabel5.setText("Usos");

        jLabel6.setText("Estado");

        btnAgregar.setText("AGREGAR");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnModificar.setText("MODIFICAR");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnBorrar.setText("BORRAR");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(JTFnumeroConsultorio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jtfCodigoConsul, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(JtfEquipamientos, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jtfUsos, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(CBEstado, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnAgregar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnModificar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnBuscar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnLimpiar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnBorrar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAgregar)
                            .addComponent(jLabel2))
                        .addGap(31, 31, 31)
                        .addComponent(btnModificar)
                        .addGap(476, 476, 476))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGap(243, 243, 243)
                                .addComponent(btnLimpiar)
                                .addGap(41, 41, 41)
                                .addComponent(btnBorrar)
                                .addGap(212, 212, 212))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(JtfEquipamientos, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfUsos, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                        .addComponent(jtfCodigoConsul, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnBuscar))
                                    .addComponent(JTFnumeroConsultorio, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(148, 148, 148)
                                .addComponent(CBEstado)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(287, 287, 287)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(JTFnumeroConsultorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfCodigoConsul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(26, 26, 26)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(JtfEquipamientos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jtfUsos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CBEstado)
                    .addComponent(jLabel6))
                .addGap(38, 38, 38)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiar)
                    .addComponent(btnBorrar)
                    .addComponent(btnModificar)
                    .addComponent(btnAgregar))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed

try {   
            ConsultorioData consultorioData = new ConsultorioData();

            // Validar DNI
            if (jtfCodigoConsul.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "El campo Codigo del consultorio no puede estar vacio.");
                return;
            }

           int cod_consultorio = Integer.parseInt(jtfCodigoConsul.getText());
            Consultorio consultorioOriginal = consultorioData.buscarConsultorio(cod_consultorio);
            if (consultorioOriginal == null) {
                JOptionPane.showMessageDialog(this, "No existe ningun consultorio con ese codigo ingresado");
                return;
            }

            // Validar demas Campos
            String equipamiento = JtfEquipamientos.getText();
            String usos =  jtfUsos.getText();
            String nro_consultorioText = JTFnumeroConsultorio.getText(); 
            

            // Validar Vacios
            if (equipamiento.isEmpty() || nro_consultorioText.isEmpty()) {
                JOptionPane.showMessageDialog(this, "El Equipamiento y el Nro Consultorio son obligatorios.");
                return;
            }
            
            int nro_consultorio = Integer.parseInt(JTFnumeroConsultorio.getText());

            //Confirmaciones
            int confirmacion = JOptionPane.showConfirmDialog(this,
                    "¿Esta seguro de modificar los datos del Consultorio " + nro_consultorio + "?",
                    "Confirmar Modificacion",
                    JOptionPane.YES_NO_OPTION);

            if (confirmacion == JOptionPane.YES_OPTION) {
                //Actualiza
                boolean estado = CBEstado.isSelected();
                Consultorio consultorio = new Consultorio(cod_consultorio, nro_consultorio, equipamiento, usos, estado);

                Consultorio consultorioModificado = new Consultorio(cod_consultorio, nro_consultorio, equipamiento, usos, estado);

                //Traer ID del cliente BD
                consultorioModificado.setCodConsultorio(consultorioOriginal.getCodConsultorio());

                consultorioData.actualizarConsultorio(consultorioModificado);
                JOptionPane.showMessageDialog(this, "Consultorio modificado.");
                limpiarCampos();
            }

        } catch (NumberFormatException e) {
            // atrapa Errores Edad y DNI
            JOptionPane.showMessageDialog(this, "Error de formato: Verifique que el Num Consultorio y el Codigo contengan solo numeros enteros.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrio un error inesperado: " + e.getMessage());
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
try {
            String equipamiento = JtfEquipamientos.getText();
            String usos =  jtfUsos.getText();
           
            if (equipamiento.isEmpty()) {
                JOptionPane.showMessageDialog(this, "El campo Equipamiento no puede estar vacio.");
                return;
            }

            if (JTFnumeroConsultorio.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Debe completar el campo Num Consultorio.");
                return;
            }

            int nro_consultorio = Integer.parseInt(JTFnumeroConsultorio.getText());
            boolean estado = CBEstado.isSelected();

            ConsultorioData consultorioData = new ConsultorioData();
            Consultorio consultorio = new Consultorio(nro_consultorio, equipamiento, usos, estado);
            consultorioData.agregarConsultorio(consultorio);

            JOptionPane.showMessageDialog(this, "Consultorio agregado exitosamente.");
            //limpiaCampos
            limpiarCampos();

        } catch (NumberFormatException e) {
            // Este error salta si el DNI o la Edad tienen letras o simbolos
            JOptionPane.showMessageDialog(this, "Error de formato: Verifique que el Nro de Consultorio sea un numero.");
        } catch (Exception e) {
            // Captura errores inesperados
            JOptionPane.showMessageDialog(this, "Ocurrio un error al guardar: " + e.getMessage());
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
 try {
            ConsultorioData consultorioData = new ConsultorioData();
            int codigoConsultorio = Integer.parseInt(jtfCodigoConsul.getText());
            Consultorio consultorio = consultorioData.buscarConsultorio(codigoConsultorio);
            if (consultorio != null) {
                jtfCodigoConsul.setText(String.valueOf(consultorio.getCodConsultorio()));
                JTFnumeroConsultorio.setText(String.valueOf(consultorio.getNroConsultorio()));
               JtfEquipamientos.setText(consultorio.getEquipamiento());
               jtfUsos.setText(consultorio.getUsos());
               CBEstado.setSelected(consultorio.isEstado());

            if (!consultorio.isEstado()) {
            JOptionPane.showMessageDialog(this, "Este consultorio figura como Inactivo/Dado de baja.");
        }    
            } else {
                JOptionPane.showMessageDialog(this, "No se encuentra el Consultorio ingresado: "+ codigoConsultorio);
                limpiarCampos();
                //Mantener el Campo DNI Escrito
                jtfCodigoConsul.setText(String.valueOf(codigoConsultorio));
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ingrese un num Valido para Buscar Consultorios");
        jtfCodigoConsul.setText("");
        }catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Error al buscar: " + e.getMessage());
}
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
       limpiarCampos(); 
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
try {
            if (jtfCodigoConsul.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Debe ingresar un Codigo de consultorio borrar.");
                return;
            }

             int codigoConsultorio = Integer.parseInt(jtfCodigoConsul.getText());
            ConsultorioData consultorioData = new ConsultorioData();

            Consultorio consultorioEncontrado = consultorioData.buscarConsultorio(codigoConsultorio);

            if (consultorioEncontrado != null) {

                int respuesta = JOptionPane.showConfirmDialog(this,
                        "¿Esta seguro que desea eliminar el Consultorio " + consultorioEncontrado.getNroConsultorio() + "?",
                        "Confirmar",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.WARNING_MESSAGE);

                if (respuesta == JOptionPane.YES_OPTION) {
                    consultorioData.eliminarConsultorio(codigoConsultorio);

                    JOptionPane.showMessageDialog(this, "Consultorio eliminado.");
                    limpiarCampos();
                }

            } else {
                JOptionPane.showMessageDialog(this, "No se encuentra un Consultorio con ese codigo.");
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ingrese un num valido en el campo consultorio.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al eliminar: " + e.getMessage());
        }
    }//GEN-LAST:event_btnBorrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionConsultorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionConsultorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionConsultorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionConsultorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionConsultorios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CBEstado;
    private javax.swing.JTextField JTFnumeroConsultorio;
    private javax.swing.JTextField JtfEquipamientos;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jtfCodigoConsul;
    private javax.swing.JTextField jtfUsos;
    // End of variables declaration//GEN-END:variables
}
