/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.Instalacion;
import Persistencia.InstalacionData;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author abate
 */
public class InstalacionMasSolicitada extends javax.swing.JInternalFrame {

    private ArrayList<Instalacion> listaT;
    private InstalacionData instalaciondata;
    private DefaultTableModel modeloTabla;

    public InstalacionMasSolicitada() {
        initComponents();

        instalaciondata = new InstalacionData();
        listaT = (ArrayList<Instalacion>) instalaciondata.listarInstalaciones();

        modeloTabla = new DefaultTableModel();
        cargarColumnasTablas();
        cargarInstalacion();
        cargarTablaMasUsadas();
    }

//     Cargar los valores del enum en el combo
    public void cargarInstalacion() {

        jCbInstalaciones.removeAllItems();
        jCbInstalaciones.addItem("Seleccione un tipo...");

        for (Instalacion instalacion : instalaciondata.listarInstalaciones()) {
            jCbInstalaciones.addItem(instalacion.toString());
        }

    }

    // Definir columnas de la tabla
    private void cargarColumnasTablas() {
        modeloTabla.addColumn("Nombre");
        modeloTabla.addColumn("Detalle Uso");
        modeloTabla.addColumn("Precio");
        modeloTabla.addColumn("Sesiones Usadas");
        jTabInstalaciones.setModel(modeloTabla);
    }
    //Limpia la tabla para dar paso a los nuevos elementos
    private void borrarFilaTabla() {
        int indice = modeloTabla.getRowCount() - 1;
        for (int i = indice; i >= 0; i--) {
            modeloTabla.removeRow(i);
        }
    }

    //Carga la tabla con el metodo obtener instalaciones
    private void cargarTablaMasUsadas() {
        borrarFilaTabla();

        String seleccionado = (String) jCbInstalaciones.getSelectedItem();
        if (seleccionado == null || seleccionado.equals("Seleccione un tipo...")) {
            return;
        }
        try {
            listaT = (ArrayList<Instalacion>) instalaciondata.obtenerInstalacionesMasUsadas();
        
        // Validación de lista vacía
        if (listaT == null || listaT.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No se encontraron instalaciones para mostrar.");
            return;
        }
            for (Instalacion instalacion : listaT) {
                modeloTabla.addRow(new Object[]{
                    instalacion.getNombre(),
                    instalacion.getDetalleUso(),
                    instalacion.getPrecio(),
                    instalacion.getCont()
                });
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al obtener instalaciones: " + e.getMessage());
            return;

        }
    
    } 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCbInstalaciones = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabInstalaciones = new javax.swing.JTable();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);

        jLabel1.setFont(new java.awt.Font("SimSun", 1, 20)); // NOI18N
        jLabel1.setText("Instalacion mas Solicitadas");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Seleccione la Instalacion: ");

        jCbInstalaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbInstalacionesActionPerformed(evt);
            }
        });

        jTabInstalaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTabInstalaciones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCbInstalaciones, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jLabel1)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCbInstalaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(55, 55, 55)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCbInstalacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbInstalacionesActionPerformed
        // TODO add your handling code here:
        cargarTablaMasUsadas();
    }//GEN-LAST:event_jCbInstalacionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InstalacionMasSolicitada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InstalacionMasSolicitada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InstalacionMasSolicitada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InstalacionMasSolicitada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InstalacionMasSolicitada().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jCbInstalaciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabInstalaciones;
    // End of variables declaration//GEN-END:variables
}
