/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Estilo.EstiloVisual;
import Modelo.Instalacion;
import Persistencia.InstalacionData;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author abate
 */
public class InstalacionMasSolicitada extends javax.swing.JInternalFrame {

    private ArrayList<Instalacion> listaT;
    private InstalacionData instalaciondata;
    
    private DefaultTableModel modeloTabla;

    public InstalacionMasSolicitada() {
        initComponents();
        EstiloVisual.aplicarEstiloJDPanel(jDesktopPane1);
        EstiloVisual.aplicarEstiloTabla(jTabInstalaciones);

        instalaciondata = new InstalacionData();
        listaT = (ArrayList<Instalacion>) instalaciondata.listarInstalaciones();

        modeloTabla = new DefaultTableModel();
        cargarColumnasTablas();
        configurarModeloTabla(false);
        cargarInstalacion();
        cargarTablaMasUsadas();
       
    }

    private void configurarModeloTabla(boolean mostrarColumnaSesiones) {
        modeloTabla = new DefaultTableModel();
        modeloTabla.addColumn("Nombre");
        modeloTabla.addColumn("Detalle Uso");
        modeloTabla.addColumn("Precio");

       //booleano true, carga sesiones
        if (mostrarColumnaSesiones) {
            modeloTabla.addColumn("Sesiones Usadas");
        }

        jTabInstalaciones.setModel(modeloTabla);
    }
        
//     Cargar los valores del enum en el combo
    public void cargarInstalacion() {

        jCbInstalaciones.removeAllItems();
        jCbInstalaciones.addItem("Seleccione un tipo...");
        jCbInstalaciones.addItem("Todas");

        java.util.HashSet<String> nombresAgregados = new java.util.HashSet<>();

        for (Instalacion instalacion : instalaciondata.listarInstalaciones()) {
            String nombre = instalacion.getNombre();

            
            if (!nombresAgregados.contains(nombre)) {
                jCbInstalaciones.addItem(nombre);
                nombresAgregados.add(nombre);
            }
        }

    }

    // Definir columnas de la tabla
    private void cargarColumnasTablas() {
        modeloTabla.addColumn("Nombre");
        modeloTabla.addColumn("Detalle Uso");
        modeloTabla.addColumn("Precio");
        modeloTabla.addColumn("Sesiones Usadas");
        jTabInstalaciones.setModel(modeloTabla);
    }
    //Limpia la tabla para dar paso a los nuevos elementos
    private void borrarFilaTabla() {
        int indice = modeloTabla.getRowCount() - 1;
        for (int i = indice; i >= 0; i--) {
            modeloTabla.removeRow(i);
        }
    }

    //Carga la tabla con el metodo obtener instalaciones
    private void cargarTablaMasUsadas() {
        borrarFilaTabla();
    String seleccion = (String) jCbInstalaciones.getSelectedItem();
    if (seleccion == null || seleccion.equals("Seleccione un tipo...")) {
        return;
    }


        try {
            if (seleccion.equals("Todas")) { 
            configurarModeloTabla(false);
            listaT = (ArrayList<Instalacion>) instalaciondata.listarInstalaciones();
            
            if (listaT != null) {
                for (Instalacion instalacion : listaT) {
                    modeloTabla.addRow(new Object[]{
                        instalacion.getNombre(),
                        instalacion.getDetalleUso(),
                        instalacion.getPrecio()
                        
                    });
                }
            }
        } else {
            configurarModeloTabla(true);
            listaT = (ArrayList<Instalacion>) instalaciondata.obtenerInstalacionesMasUsadas(seleccion);
        
        // Validación de lista vacía
        if (listaT == null || listaT.isEmpty()) {
            return;
        }
            for (Instalacion instalacion : listaT) {
                modeloTabla.addRow(new Object[]{
                    instalacion.getNombre(),
                    instalacion.getDetalleUso(),
                    instalacion.getPrecio(),
                    instalacion.getCont()
                });
            }
            }
        }catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al obtener instalaciones: " + e.getMessage());
            return;

        }
    
    } 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCbInstalaciones = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabInstalaciones = new javax.swing.JTable();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);

        jLabel1.setFont(new java.awt.Font("SimSun", 1, 20)); // NOI18N
        jLabel1.setText("Instalacion mas Solicitadas");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Seleccione la Instalacion: ");

        jCbInstalaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbInstalacionesActionPerformed(evt);
            }
        });

        jTabInstalaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTabInstalaciones);

        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jCbInstalaciones, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCbInstalaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(88, Short.MAX_VALUE))
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCbInstalaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(53, 53, 53)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCbInstalacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbInstalacionesActionPerformed
        // TODO add your handling code here:
        cargarTablaMasUsadas();
    }//GEN-LAST:event_jCbInstalacionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InstalacionMasSolicitada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InstalacionMasSolicitada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InstalacionMasSolicitada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InstalacionMasSolicitada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InstalacionMasSolicitada().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jCbInstalaciones;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabInstalaciones;
    // End of variables declaration//GEN-END:variables
}
